### ISSUE TITLE
 No module named 'pair wise distance cuda‘这个库在哪里下载

### ISSUE THREAD

**Issue by Tate2099** [DotWang/DCN-T#5]
如题

**Comment by DotWang** [comment]
@Tate2099 看readme，ssn要手动安装

**Comment by Tate2099** [comment]
手动安装ssn时报错。请问大佬如何解决？
RuntimeError: Error compiling objects for extension

**Comment by Tate2099** [comment]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zl/Desktop/DCN-T-main/utils/gensp/src/setup.py", line 4, in <module>
    setup(
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/setuptools/__init__.py", line 155, in setup
    return distutils.core.setup(**attrs)
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/setuptools/command/install.py", line 116, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/setuptools/_distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
    build_ext.build_extensions(self)
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 586, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1487, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1824, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by Tate2099** [comment]
解决了，是pytorch版本问题。。。要求pytorch版本大于1.6小于1.9

**Comment by Tate2099** [comment]
pair wise distance cuda这个库还是有问题。。。。请问怎么解决？

NOTE: if you avoid this process, you make .cu file and compile it following https://pytorch.org/tutorials/advanced/cpp_extension.html
done
Traceback (most recent call last):
  File "/home/zl/Desktop/DCN-T-main/train_memory.py", line 503, in &lt;module&gt;
    main()
  File "/home/zl/Desktop/DCN-T-main/train_memory.py", line 461, in main
    trainer = Trainer(args,LOCAL_RANK)
  File "/home/zl/Desktop/DCN-T-main/train_memory.py", line 109, in __init__
    from models.network_local_global import rat_model
  File "/home/zl/Desktop/DCN-T-main/models/network_local_global.py", line 8, in &lt;module&gt;
    from utils.gensp.ssn_sp import ssn_iter
  File "/home/zl/Desktop/DCN-T-main/utils/gensp/ssn_sp.py", line 4, in &lt;module&gt;
    from .pair_wise_distance import PairwiseDistFunction
  File "/home/zl/Desktop/DCN-T-main/utils/gensp/pair_wise_distance.py", line 13, in &lt;module&gt;
    import pair_wise_distance_cuda
ImportError: /home/zl/anaconda3/envs/lusong/lib/python3.9/site-packages/pair_wise_distance-0.0.0-py3.9-linux-x86_64.egg/pair_wise_distance_cuda.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c107complexIfEEEEPKNS_6detail12TypeMetaDataEv
Killing subprocess 16140
